sudo: false

language: node_js
node_js:
  - 9

addons:
  sonarcloud:
    organization: "Nuna"
    token: "a58963ab62716362a6e03b1d258fa8415c0fbd5a"

script:
  - sonar-scanner -X
  - npm run coveralls
branches:
  only:
    - master
