sudo: false

language: node_js
node_js:
  - 9

addons:
  sonarcloud:
    organization: "120798"
    token: "cc8c17f6370ed8ad0924b3c167fab46af2272bbf"

script:
  - sonar-scanner -X
  - npm run coveralls
branches:
  only:
    - master
